apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: default
  annotations:
spec:
  accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
